#!/usr/bin/env node
/**
 * Converts imported PHOTO*.png in public/gallery/_import/ to optimized
 * dr-rf-XX.webp + dr-rf-XX.avif in public/gallery/
 * and writes src/data/galleryManifest.ts for the React app.
 */
import sharp from 'sharp';
import { readdir, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const IMPORT = path.join(ROOT, 'public/gallery/_import');
const OUT = path.join(ROOT, 'public/gallery');

const MAX = 1920;

async function processOne(inputPath, baseName) {
  const meta = await sharp(inputPath).metadata();
  const w0 = meta.width || 1;
  const h0 = meta.height || 1;
  const long = Math.max(w0, h0);
  let pipeline = sharp(inputPath).rotate();
  if (long > MAX) {
    pipeline = pipeline.resize({
      width: w0 >= h0 ? MAX : null,
      height: h0 > w0 ? MAX : null,
      fit: 'inside',
      withoutEnlargement: true,
    });
  }
  const { data, info } = await pipeline.toBuffer({ resolveWithObject: true });
  const w = info.width;
  const h = info.height;

  const webpPath = path.join(OUT, `${baseName}.webp`);
  const avifPath = path.join(OUT, `${baseName}.avif`);
  await sharp(data).webp({ quality: 78, effort: 6 }).toFile(webpPath);
  await sharp(data).avif({ quality: 45, effort: 4 }).toFile(avifPath);

  return { w, h };
}

async function main() {
  await mkdir(OUT, { recursive: true });
  let files = (await readdir(IMPORT)).filter((f) => /\.png$/i.test(f));
  files.sort();
  if (files.length === 0) {
    console.error('No PNG files in', IMPORT);
    process.exit(1);
  }

  const items = [];
  for (let i = 0; i < files.length; i++) {
    const num = String(i + 1).padStart(2, '0');
    const base = `dr-rf-${num}`;
    const input = path.join(IMPORT, files[i]);
    const { w, h } = await processOne(input, base);
    items.push({
      id: base,
      webp: `/gallery/${base}.webp`,
      avif: `/gallery/${base}.avif`,
      width: w,
      height: h,
      alt: `Dr. Roofing FL real job site — South Florida roof work photo ${i + 1} (architectural shingle, metal, or flat roof — ${
        i % 3 === 0 ? 'Broward' : i % 3 === 1 ? 'Miami-Dade' : 'South Florida'
      })`,
    });
    console.log(`  ✓ ${base}  ${w}×${h}`);
  }

  const ts = `// AUTO-GENERATED by scripts/process-gallery.mjs — do not edit by hand
export interface GalleryItem {
  id: string;
  webp: string;
  avif: string;
  width: number;
  height: number;
  alt: string;
}

export const galleryItems: readonly GalleryItem[] = ${JSON.stringify(items, null, 2)} as const;
`;
  await writeFile(path.join(ROOT, 'src/data/galleryManifest.ts'), ts, 'utf8');
  console.log(`\n✓ Wrote src/data/galleryManifest.ts (${items.length} items)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
