// AUTO-GENERATED by scripts/process-gallery.mjs — do not edit by hand
export interface GalleryItem {
  id: string;
  webp: string;
  avif: string;
  width: number;
  height: number;
  alt: string;
}

export const galleryItems: readonly GalleryItem[] = [
  {
    "id": "dr-rf-01",
    "webp": "/gallery/dr-rf-01.webp",
    "avif": "/gallery/dr-rf-01.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 1 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-02",
    "webp": "/gallery/dr-rf-02.webp",
    "avif": "/gallery/dr-rf-02.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 2 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-03",
    "webp": "/gallery/dr-rf-03.webp",
    "avif": "/gallery/dr-rf-03.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 3 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-04",
    "webp": "/gallery/dr-rf-04.webp",
    "avif": "/gallery/dr-rf-04.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 4 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-05",
    "webp": "/gallery/dr-rf-05.webp",
    "avif": "/gallery/dr-rf-05.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 5 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-06",
    "webp": "/gallery/dr-rf-06.webp",
    "avif": "/gallery/dr-rf-06.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 6 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-07",
    "webp": "/gallery/dr-rf-07.webp",
    "avif": "/gallery/dr-rf-07.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 7 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-08",
    "webp": "/gallery/dr-rf-08.webp",
    "avif": "/gallery/dr-rf-08.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 8 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-09",
    "webp": "/gallery/dr-rf-09.webp",
    "avif": "/gallery/dr-rf-09.avif",
    "width": 800,
    "height": 602,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 9 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-10",
    "webp": "/gallery/dr-rf-10.webp",
    "avif": "/gallery/dr-rf-10.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 10 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-11",
    "webp": "/gallery/dr-rf-11.webp",
    "avif": "/gallery/dr-rf-11.avif",
    "width": 602,
    "height": 800,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 11 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-12",
    "webp": "/gallery/dr-rf-12.webp",
    "avif": "/gallery/dr-rf-12.avif",
    "width": 602,
    "height": 800,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 12 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-13",
    "webp": "/gallery/dr-rf-13.webp",
    "avif": "/gallery/dr-rf-13.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 13 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-14",
    "webp": "/gallery/dr-rf-14.webp",
    "avif": "/gallery/dr-rf-14.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 14 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-15",
    "webp": "/gallery/dr-rf-15.webp",
    "avif": "/gallery/dr-rf-15.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 15 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-16",
    "webp": "/gallery/dr-rf-16.webp",
    "avif": "/gallery/dr-rf-16.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 16 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-17",
    "webp": "/gallery/dr-rf-17.webp",
    "avif": "/gallery/dr-rf-17.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 17 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-18",
    "webp": "/gallery/dr-rf-18.webp",
    "avif": "/gallery/dr-rf-18.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 18 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-19",
    "webp": "/gallery/dr-rf-19.webp",
    "avif": "/gallery/dr-rf-19.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 19 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-20",
    "webp": "/gallery/dr-rf-20.webp",
    "avif": "/gallery/dr-rf-20.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 20 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-21",
    "webp": "/gallery/dr-rf-21.webp",
    "avif": "/gallery/dr-rf-21.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 21 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-22",
    "webp": "/gallery/dr-rf-22.webp",
    "avif": "/gallery/dr-rf-22.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 22 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-23",
    "webp": "/gallery/dr-rf-23.webp",
    "avif": "/gallery/dr-rf-23.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 23 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-24",
    "webp": "/gallery/dr-rf-24.webp",
    "avif": "/gallery/dr-rf-24.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 24 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-25",
    "webp": "/gallery/dr-rf-25.webp",
    "avif": "/gallery/dr-rf-25.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 25 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-26",
    "webp": "/gallery/dr-rf-26.webp",
    "avif": "/gallery/dr-rf-26.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 26 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-27",
    "webp": "/gallery/dr-rf-27.webp",
    "avif": "/gallery/dr-rf-27.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 27 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-28",
    "webp": "/gallery/dr-rf-28.webp",
    "avif": "/gallery/dr-rf-28.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 28 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-29",
    "webp": "/gallery/dr-rf-29.webp",
    "avif": "/gallery/dr-rf-29.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 29 (architectural shingle, metal, or flat roof — Miami-Dade)"
  },
  {
    "id": "dr-rf-30",
    "webp": "/gallery/dr-rf-30.webp",
    "avif": "/gallery/dr-rf-30.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 30 (architectural shingle, metal, or flat roof — South Florida)"
  },
  {
    "id": "dr-rf-31",
    "webp": "/gallery/dr-rf-31.webp",
    "avif": "/gallery/dr-rf-31.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 31 (architectural shingle, metal, or flat roof — Broward)"
  },
  {
    "id": "dr-rf-32",
    "webp": "/gallery/dr-rf-32.webp",
    "avif": "/gallery/dr-rf-32.avif",
    "width": 768,
    "height": 1024,
    "alt": "Dr. Roofing FL real job site — South Florida roof work photo 32 (architectural shingle, metal, or flat roof — Miami-Dade)"
  }
] as const;
