/**
 * Groups every city in `locations.ts` into the 3 South Florida counties
 * we serve — used by Header + Footer navigation menus.
 *
 * For cities generated by `cityBuilder` the county lives in
 * `cityFacts` (`{ label: 'County', value: 'Broward County' }`).
 *
 * For the 9 hand-authored cities we keep a static fallback map below.
 */

import { locationList, type LocationData } from './locations';

export type County = 'Palm Beach County' | 'Broward County' | 'Miami-Dade County';

const HAND_AUTHORED_COUNTY: Record<string, County> = {
  hollywood: 'Broward County',
  miami: 'Miami-Dade County',
  'fort-lauderdale': 'Broward County',
  'pembroke-pines': 'Broward County',
  miramar: 'Broward County',
  davie: 'Broward County',
  'hallandale-beach': 'Broward County',
  'dania-beach': 'Broward County',
  aventura: 'Miami-Dade County',
};

export function countyFor(location: LocationData): County {
  const fromFacts = location.cityFacts.find((f) => f.label === 'County')?.value;
  if (fromFacts && fromFacts.endsWith('County')) return fromFacts as County;
  return HAND_AUTHORED_COUNTY[location.citySlug] ?? 'Broward County';
}

export interface CountyGroup {
  county: County;
  cities: LocationData[];
}

/**
 * Ordered groups: Broward → Miami-Dade → Palm Beach.
 * Cities inside each group are alphabetized.
 */
export const locationsByCounty: CountyGroup[] = (() => {
  const bucket: Record<County, LocationData[]> = {
    'Broward County': [],
    'Miami-Dade County': [],
    'Palm Beach County': [],
  };

  for (const loc of locationList) {
    bucket[countyFor(loc)].push(loc);
  }

  for (const key of Object.keys(bucket) as County[]) {
    bucket[key].sort((a, b) => a.city.localeCompare(b.city));
  }

  return [
    { county: 'Broward County', cities: bucket['Broward County'] },
    { county: 'Miami-Dade County', cities: bucket['Miami-Dade County'] },
    { county: 'Palm Beach County', cities: bucket['Palm Beach County'] },
  ];
})();

/** Flattened helper — all cities alphabetized globally */
export const locationsAlphabetical = [...locationList].sort((a, b) =>
  a.city.localeCompare(b.city)
);

/** Primary / flagship cities to feature in hero / above-the-fold spots */
export const flagshipCitySlugs = [
  'hollywood',
  'miami',
  'fort-lauderdale',
  'pembroke-pines',
  'miramar',
  'davie',
  'hallandale-beach',
  'dania-beach',
  'aventura',
  'boca-raton',
  'west-palm-beach',
  'coral-gables',
];

export const flagshipCities: LocationData[] = flagshipCitySlugs
  .map((slug) => locationList.find((l) => l.citySlug === slug))
  .filter((l): l is LocationData => !!l);
